# Site settings
title: Your Name - Portfolio
email: your-email@example.com
description: >- 
  A showcase of my projects and blog posts.
baseurl: "" 
url: "" 
twitter_username: your_twitter_handle
github_username:  your_github_username

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: pages-themes/architect@v0.2.0

# Layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Projects collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing.
exclude:
  - vault-blog
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# Navigation
header_pages:
  - about.md
  - projects.md
  - blog.md